### ISSUE TITLE
SharePoint deployment files

### ISSUE THREAD

**Issue by adiazcan** [OfficeDev/Virtual-Health-Templates#1]
Hi!

I'm triying to test this wonderfull sample but I can't find the .aspx and .xml files from SharePoint Deployment step. 

Any way to get them?

**Comment by ritesp** [comment]
Thanks, we have included these files as part of deployment tool.

https://github.com/OfficeDev/Virtual-Health-Templates/blob/master/VirtualHealthDeploymentTool.zip

Regards,
Ritesh

**Comment by adiazcan** [comment]
thanks!!!!!
