### ISSUE TITLE
TS2307 Cannot find module '@angular/core'. 

### ISSUE THREAD

**Issue by chamodh** [OfficeDev/Virtual-Health-Templates#6]
Hi ,

I downloaded the virtual-Health-Template to my local machine and opened it in VS 2015 community edition. But the moment i opened the project its showing that "angular/core" is missing. i`m confused how to solve this. Your help is highly appreciated !

**Comment by JamesIgoe** [comment]
chamood, how did you solve this issue?

**Comment by chamodh** [comment]
@JamesIgoe yes the issue was with the nuget packages. After restoring all the packages i could fix the issue.
